version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - LAST_FM_API_KEY=key
      - LAST_FM_SHARED_SECRET=key
      - LAST_FM_SESSION_KEY=key
      - WEBHOOK_API_KEY=key
